---
name: "WF-1"
on:
  push:

# JOBS
jobs:
  Job1:
    name: Job  named  Job1
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-18.04, ubuntu-20.04]
      python: [3.7, 3.8, 3.9]
    services:
      mysql:
        image: mysql:5.7.36
        env:
          MYSQL_ROOT_PASSWORD:  "1234567"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Python version
        run: |
          python --version

  Job2:
    name: Job  named  Job2
    runs-on: ubuntu-latest
    needs: [Job1]
    steps:
      - uses: actions/checkout@v2
      - name: bash ls
        run: |
          ls -alh
      - name: Python version
        run: |
          python --version