name: Monorepo-wf-1

on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'List the modules to build, white space delimited'
        required: true

  push:
 #   branches:
 #     - '**'
  pull_request:
    branches:
      - master
    types:
      - closed



concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }} 
  cancel-in-progress: true

jobs:
  
  initialize_ci:
    runs-on: ubuntu-20.04
    outputs:
      pr_number: ${{ steps.findPr.outputs.number }}
    steps:
      - uses: hmarr/debug-action@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

        
      - name: pr
        id: pr
        run: |
           CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
           LATEST_PR=$(gh pr list --state merged --base $CURRENT_BRANCH --limit 1 | awk '{print $3}')
           LATEST_COMMIT=$(git rev-parse HEAD)
           LATEST_PR_COMMIT=$(gh pr list --state merged --base $CURRENT_BRANCH --json number,title,body,labels,assignees,mergeCommit |jq -r '.[0].mergeCommit.oid')
           echo "LATEST_PR=$LATEST_PR"
            echo "LATEST_COMMIT=$LATEST_COMMIT"
            echo "LATEST_PR_COMMIT=$LATEST_PR_COMMIT"
           if [ "$LATEST_COMMIT" != "$LATEST_PR_COMMIT" ]; then
            echo "There have been direct commits to $TARGET_BRANCH after the last pull request was merged."
           else
            echo "No direct commits to $TARGET_BRANCH after the last pull request was merged."
            echo "pr_branch=$LATEST_PR" >> $GITHUB_OUTPUT
           fi
        env:
          GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open

      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "$PR"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ toJson(steps.findPr.outputs) }}

  changes:
    name: Get changes
    runs-on: ubuntu-20.04
    needs:
      - initialize_ci

    outputs:
      matrix: "{\"services\": ${{ steps.reduce.outputs.services }} }"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            changed:
            - './*/**'
            - './.github/**'
      - name: Store changed files in file
        run: echo '${{ toJson(steps.filter.outputs) }}' > changes.json

      - name: Get changed apps
        id: reduce
        run: |
          echo "${{ toJson(steps.filter.outputs) }}"
          # .changed_files | fromjson | .[] |= sub("(?<first_directory>(?<root2>[/]?)[^/]+)(?<extra_paths>.+)"; "\(.first_directory)") | unique
          # https://jqplay.org/s/HSOZ2Duk7l
          SVC=$(jq -c --raw-output '.changed_files | fromjson | .[] |= sub("(?<filepath>(?<first_directory>(?<root1>[/]?)[^/]+)/(?<second_directory>(?<root2>[/]?)[^/]+)(?<extra_paths>.+))"; "\(.first_directory)") | unique' changes.json)
          echo "$APPS"
          echo "::set-output name=services::${SVC}"

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs:
      - changes
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.matrix) }}
      fail-fast: false
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2


        